// Generated by tools/generate_timezone_table.py -- do not hand-edit.
#pragma once

#include <stddef.h>

typedef struct {
  const char *iana_name;
  const char *posix_name;
} timezone_mapping_t;

extern const timezone_mapping_t TIMEZONE_MAPPINGS[];
extern const size_t TIMEZONE_MAPPINGS_COUNT;
