#!/usr/bin/env python3
"""Generates a full IANA -> POSIX TZ mapping table for the ESP32-P4 firmware.

ESP-IDF/newlib does not ship a zoneinfo database, so `setenv("TZ", ...)`
with a raw IANA name (e.g. "Asia/Tokyo") does not give correct DST/offset
behavior on-device -- it needs the POSIX TZ string form (e.g. "JST-9").

Rather than hand-maintaining a short whitelist, this reads the POSIX TZ
string straight out of each zone's real TZif file (the same file the host
system's own C library uses), via the standard "footer" that TZif v2/v3
files embed for exactly this purpose (RFC 8536 section 3.3). That makes
this table only as good as the host machine's own tzdata -- run this on a
reasonably up-to-date Linux or macOS system to regenerate it.

Usage:
    python3 generate_timezone_table.py --output-c main/timezone_table.c --output-h main/timezone_table.h
"""

from __future__ import annotations

import argparse
import struct
import zoneinfo
from pathlib import Path

ZONEINFO_ROOT = Path("/usr/share/zoneinfo")


def read_tzif_footer(path: Path) -> str | None:
    data = path.read_bytes()

    def parse_header(offset: int):
        if data[offset:offset + 4] != b"TZif":
            raise ValueError(f"not a TZif file: {path}")
        version = data[offset + 4:offset + 5]
        counts = struct.unpack(">6l", data[offset + 20:offset + 44])
        return version, counts

    version, (isutcnt, isstdcnt, leapcnt, timecnt, typecnt, charcnt) = parse_header(0)
    v1_data_size = timecnt * 4 + timecnt * 1 + typecnt * 6 + charcnt + leapcnt * 8 + isstdcnt + isutcnt
    v1_total = 44 + v1_data_size

    if version not in (b"2", b"3"):
        return None

    _, (isutcnt2, isstdcnt2, leapcnt2, timecnt2, typecnt2, charcnt2) = parse_header(v1_total)
    v2_data_size = timecnt2 * 8 + timecnt2 * 1 + typecnt2 * 6 + charcnt2 + leapcnt2 * 12 + isstdcnt2 + isutcnt2
    v2_data_end = v1_total + 44 + v2_data_size

    if data[v2_data_end:v2_data_end + 1] != b"\n":
        return None
    end_nl = data.index(b"\n", v2_data_end + 1)
    footer = data[v2_data_end + 1:end_nl].decode("ascii")
    return footer or None


def build_table() -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    for name in sorted(zoneinfo.available_timezones()):
        path = ZONEINFO_ROOT / name
        if not path.is_file():
            continue
        posix = read_tzif_footer(path)
        if not posix:
            continue
        entries.append((name, posix))
    return entries


def escape_c_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_c(entries: list[tuple[str, str]]) -> str:
    lines = [
        "// Generated by tools/generate_timezone_table.py -- do not hand-edit.",
        "// Regenerate after a tzdata update on the host machine.",
        "",
        '#include "timezone_table.h"',
        "",
        "const timezone_mapping_t TIMEZONE_MAPPINGS[] = {",
    ]
    for iana, posix in entries:
        lines.append(f'  {{"{escape_c_string(iana)}", "{escape_c_string(posix)}"}},')
    lines.append("};")
    lines.append("")
    lines.append(
        "const size_t TIMEZONE_MAPPINGS_COUNT = sizeof(TIMEZONE_MAPPINGS) / sizeof(TIMEZONE_MAPPINGS[0]);"
    )
    lines.append("")
    return "\n".join(lines)


def render_h() -> str:
    return """// Generated by tools/generate_timezone_table.py -- do not hand-edit.
#pragma once

#include <stddef.h>

typedef struct {
  const char *iana_name;
  const char *posix_name;
} timezone_mapping_t;

extern const timezone_mapping_t TIMEZONE_MAPPINGS[];
extern const size_t TIMEZONE_MAPPINGS_COUNT;
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-c", required=True)
    parser.add_argument("--output-h", required=True)
    args = parser.parse_args()

    entries = build_table()
    if len(entries) < 400:
        raise SystemExit(
            f"Only resolved {len(entries)} timezones from {ZONEINFO_ROOT} -- "
            "that's suspiciously low, refusing to write a stale/broken table."
        )

    output_c = Path(args.output_c)
    output_h = Path(args.output_h)
    output_c.parent.mkdir(parents=True, exist_ok=True)
    output_h.parent.mkdir(parents=True, exist_ok=True)
    output_c.write_text(render_c(entries), encoding="utf-8")
    output_h.write_text(render_h(), encoding="utf-8")
    print(f"Wrote {len(entries)} timezone mappings to {output_c} and {output_h}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
